### ISSUE TITLE
Add support for global plugins

### ISSUE THREAD

**Issue by gunnarlium** [guzzle/guzzle-silex-extension#16]
I would like to be able to define global plugins, which will be added to all services, similar to the "generic" client.

When setting up Silex\Application, I would like to do something like this:

```PHP
$app['guzzle.plugins'] = function () use ($app) {
    $logAdapter = new MonologLogAdapter($app['logger']);
    $logFormatter = new MessageFormatter('{code} {method} {url} in {total_time}s');
    $logPlugin = new LogPlugin($logAdapter, $logFormatter);

    return array($logPlugin);
};
```

And then have logging enabled for all clients.

I can make this work by adding a couple of lines to the GuzzleServiceProvider->register method:

```PHP
// Register a Guzzle ServiceBuilder
$app['guzzle'] = $app->share(function () use ($app) {
    if (!isset($app['guzzle.services'])) {
        $builder = new ServiceBuilder(array());
    } else {
        $builder = ServiceBuilder::factory($app['guzzle.services']);
    }

    // I added this
    foreach ($app['guzzle.plugins'] as $plugin) {
        $builder->addGlobalPlugin($plugin);
    }

    return $builder;
});

```

I'm quite new to Guzzle, so it might be that I'm missing some better way to define plugins for services. If this way makes sense, I can create a pull request with the changes and some docs.

**Comment by mtdowling** [comment]
This repo is no longer maintained.
